<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_resultCalculator</name>
   <tag></tag>
   <elementGuidId>4c4d3f0d-6394-478e-bb15-5838a64ef62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cwos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cwos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb5e84de-56a5-4753-bf56-e3dd3fe8e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>VssY5c</value>
      <webElementGuid>e59a5a65-11e4-4006-a121-18f00a1bd5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qv3Wpe</value>
      <webElementGuid>30fae09f-6417-4a12-bd66-c80d664b516a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cwos</value>
      <webElementGuid>712bb498-7d5c-4d71-86c1-5afc7ff967d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>831f18cb-7bba-4160-903b-af62fd0e7673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cwos&quot;)</value>
      <webElementGuid>5196ff28-087c-42d9-b65d-ba02e8648613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cwos']</value>
      <webElementGuid>1cf8a93f-d116-46f5-9b51-12f35063faf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/div/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>58e13a0e-329a-4d20-8d82-9028d6e9ea9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitungan dan hasil Anda ditampilkan di sini sehingga Anda dapat menggunakannya kembali'])[1]/following::span[3]</value>
      <webElementGuid>fa950e0c-1b7f-4f6a-88e6-7a5221ec748b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Kalkulator'])[1]/following::span[4]</value>
      <webElementGuid>734746dd-5802-4ce9-864e-54bfc4b76d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rad'])[1]/preceding::span[1]</value>
      <webElementGuid>44323f82-00f7-42e3-af25-af5db1b8d4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deg'])[1]/preceding::span[1]</value>
      <webElementGuid>e1c34178-f5cb-489d-a935-dbe6bfd297c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>8af896a6-4fe5-49c6-bd5e-47f52fb06e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>9438a33c-3b5d-4641-bd3d-048ed68d59a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cwos' and (text() = '4' or . = '4')]</value>
      <webElementGuid>7eb41734-4b01-4262-b0aa-f5d0ff065000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
