<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4</name>
   <tag></tag>
   <elementGuidId>fb259937-c187-4717-8d5f-0f9efc9882cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cwos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cwos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d487e0f-17b2-4a78-81b2-a9d471da779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>VssY5c</value>
      <webElementGuid>28158adf-949f-48b6-8ac8-1f4445bcda17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qv3Wpe</value>
      <webElementGuid>7b2257c0-4d01-42c8-a59a-dd49c5d78cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cwos</value>
      <webElementGuid>0624e98d-dfe1-41f9-9976-be78e694066f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>943bb4b5-1ab0-427c-ae84-47e91fc4a8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cwos&quot;)</value>
      <webElementGuid>86438f5c-e5ef-4988-87d0-7c9ef972281b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cwos']</value>
      <webElementGuid>343b6e01-b2c5-4c07-a0b7-568c72c25c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/div/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>d1fb4157-27fb-4c74-bbb4-7e6088bee47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitungan dan hasil Anda ditampilkan di sini sehingga Anda dapat menggunakannya kembali'])[1]/following::span[3]</value>
      <webElementGuid>6fbf4a28-79b3-4133-a89f-aa6f4c109b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Kalkulator'])[1]/following::span[4]</value>
      <webElementGuid>4af2ef9a-cfa9-42fb-8d44-50b525a9b62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rad'])[1]/preceding::span[1]</value>
      <webElementGuid>bf45d738-9b3d-46bf-9404-6e23a1d3bd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deg'])[1]/preceding::span[1]</value>
      <webElementGuid>41be70ca-308f-438a-96bc-2e97ccec08d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>582587f9-7f00-49e4-96fe-953831cd8a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>ca79ed5e-2571-4938-bac3-a5840f20fc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cwos' and (text() = '4' or . = '4')]</value>
      <webElementGuid>69be87c2-3a2a-41fb-b5eb-893f0fc08081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
